# Unit 1: Language basics and NumPy

In this unit we start exploring the Python language,
covering the following topics:
1. Basic syntax
2. Built-in data types
3. NumPy arrays

## Basic syntax

- Everything after a # character (until the end of the line) is a comment and will be ignored.
- Whitespace characters matter (unlike in most languages)!
    Python uses indentation (usually 4 spaces) to group statements,
    for example loop bodies, functions, etc.
- You don't need to add a character to terminate a line, unlike in some languages.
- You can use the `print()` function to inspect almost any object.

In [1]:
# First example

# create a variable named 'text' that stores the string 'Hello, world!'
text = 'Hello, world!'

# print contents of 'text'
print(text)

Hello, world!


In IPython notebooks and command-liny Python interpreters,
we can also display a value by simply writing the variable name.

In [2]:
text

'Hello, world!'

This does not do anything in *proper* python script files
that are run through the interpreter, though.

## Built-in data types

Pythons is a dynamically-typed language:
- Unlike in C or Fortran, you don't need to declare a variable or its type

You can inspect a variable's type using the built-in `type()` function.

We now look at the most useful built-in data types:

**Basic types**
- integers (`int`)
- floating-point numbers (`float`)
- strings (`str`)

**Containers (or collections)**
- tuples (`tuple`)
- lists (`list`)
- dictionaries (`dict`)

### Integers and floats

In [3]:
# Integer variables
i = 1
type(i)

int

In [4]:
# Floating-point variables
x = 1.0
type(x)

float

In [5]:
# A name can reference any data type:
# Previously, x was a float, now it's an integer!
x = 1
type(x)

int

It is good programming practice to specify floating-point
literals using a decimal point. It makes a difference in
a few cases (especially when using NumPy arrays, Numba or Cython).

In [6]:
x = 1.0 # instead of x = 1

### Strings

The string data type stores sequences of characters.

In [7]:
# Strings need to be surrounded by single (') or double (") quotes!
institution = 'University of Glasgow'
institution = "University of Glasgow"


### Tuples

Tuples represent a collection of several items which can
have different data types. They are created using parenthesis,
`(item1, item2, ...)`.

In [8]:
# A tuple containing a string, an integer and a float
items = ('foo', 1, 1.0)
items

('foo', 1, 1.0)

The parenthesis are actually optional, but improve readability:

In [9]:
items = 'foo', 1, 1.0 # equivalent way to create a tuple
items

('foo', 1, 1.0)

Use [] to access an element in a tuple (or any other
list-like object)

In [10]:
first = items[0] # contains 'foo'
first

'foo'

Python indices are 0-based, so 0 references the first element,
1 the second element, etc.

In [11]:
second = items[1] # contains second element


Tuples are immutable, which means that the references
stored in the tuple cannot be changed!

In [12]:
%%script python --no-raise-error
# This raises an error!
items = 'foo', 1, 1.0
items[0] = 123


Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
TypeError: 'tuple' object does not support item assignment


### Lists
Lists are like tuples, expect that they can be modified.
We create lists using brackets, `[item1, item2, ...]`.

In [13]:
lst = ['foo', 1, 1.0]

Accessing list items works the same as with tuples

In [14]:
lst[0]      # print first item

'foo'

Lists items can be modified:

In [15]:
lst[0] = 'bar'
lst

['bar', 1, 1.0]

Lists are full-fledged objects that support various operations,
for example

In [16]:
lst.insert(0, 'abc')    # insert element at position 0
lst.append(2.0)         # append element at the end
del lst[3]              # delete the 4th element
lst

['abc', 'bar', 1, 2.0]

The built-in functions `len()` returns the number
of elements in a list (and any other collection object)

In [17]:
n = len(lst)
print(n)

4


### Dictionaries
Dictionaries are container objects that map keys to values.
- Both keys and values can be (almost any) Python objects,
even though usually we use strings as keys.
- Dictionaries are created using curly braces,
    `{key1: value1, key2: value2, ...}`.
- Dictionaries are unordered, ie. elements stored in dictionaries
  cannot be retrieved in any guaranteed order.

In [18]:
dct = {'institution': 'University of Glasgow',
       'course': 'Python bootcamp'}
dct

{'institution': 'University of Glasgow', 'course': 'Python bootcamp'}

Specific values are access using the syntax `dict[key]`:

In [19]:
value = dct['institution']
value

'University of Glasgow'

## NumPy arrays

NumPy is a library that allows us to efficiently store and access
(mainly) numerical data and apply numerical operations
similar to those available in Matlab.
- NumPy is not part of the core Python project
- Python itself has an array type, but there is really no
  reason to use it. Use NumPy!
- NumPy types and functions are not built-in, we must
  first import them to make them visible.
  We do this using the `import` statement.

The convention is to make NumPy functionality available
using the `np` namespace:

In [20]:
import numpy as np

### Creating arrays
NumPy offers a multitude of functions to create arrays.

In [21]:
# Create a 1-dimensional array with 10 elements, initialise values to 0
# We need to prefix the NumPy function zeros() with 'np'
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
arr1 = np.ones(5) # vector of five ones
arr1

array([1., 1., 1., 1., 1.])

We can also create sequences of integers

In [23]:
arr2 = np.arange(5) # vector [0,1,2,3,4]
arr2

array([0, 1, 2, 3, 4])

We can explicitly specify initial values and increments.
The end value is NOT included.

In [24]:
start = 2
end = 10
step = 2
arr3 = np.arange(start, end, step)
arr3

array([2, 4, 6, 8])

We can create arrays without initialisation. This
only allocates a chunk of memory, which most likely
contains arbitrary garbage.

In [25]:
arr4 = np.empty(3)
arr4 # values are unpredictable

array([4.65540513e-310, 0.00000000e+000, 3.72219086e-265])

As in Matlab, there is a `linspace()` function that
creates a vector of uniformly-spaced real values.

In [26]:
# Create 11 elements, equally spaced on the interval [0.0, 1.0]
arr5 = np.linspace(0.0, 1.0, 11)
arr5

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

We can create arrays of higher dimension by specifying
the desired shape

In [27]:
mat = np.ones((2,2)) # Create 2x2 matrix of ones
mat

array([[1., 1.],
       [1., 1.]])

#### Creating arrays from other Python objects
You can create arrays from other objects such as lists
and tuples by calling `array()`

In [28]:
# Create array from list [1,2,3]
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [29]:
# Create array from tuple
arr = np.array((1.0,2.0,3.0))
arr

array([1., 2., 3.])

In [30]:
# Create two-dimensional array from nested list
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

### Reshaping arrays
The `reshape()` method of an array object can be used
to reshape it to some other (conformable) shape.

In [31]:
mat = np.arange(4).reshape((2,2))
mat

array([[0, 1],
       [2, 3]])

In [32]:
# reshape back to vector of 4 elements
vec = mat.reshape(4)
vec

array([0, 1, 2, 3])

We can use `-1` to let NumPy automatically compute
the size of one remaining dimension.

In [33]:
# with 2 dimensions, second dimension must have size 2
mat = np.arange(4).reshape((2,-1))
mat

array([[0, 1],
       [2, 3]])

If you just want to create an arbitray array to a vector,
use the `flatten()` method.

In [34]:
mat.flatten()

array([0, 1, 2, 3])

**Important**: the reshaped array must have the same
number of elements!

In [35]:
%%script python --no-raise-error
import numpy as np
mat = np.arange(6).reshape((2,-1))
mat.reshape((2,2))      # Cannot reshape 6 into 4 elements!


Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
ValueError: cannot reshape array of size 6 into shape (2,2)


### Indexing

#### Single element indexing

To retrieve only a single element,
just use the element's index on each axis
(axis is the NumPy terminology for an array dimension).
-   Remember that just like Python in general, NumPy arrays use
    0-based indices.
-   Unlike lists or tuples, NumPy arrays support multi-dimensional
    indexing.

In [36]:
import numpy as np

mat = np.arange(6).reshape((3,2))
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [37]:
mat[1,1]    # returns element in row 2, column 2

3

It is important that we pass multi-dimensional indices as a
tuple to within brackets, ie `[1,1]` in the above example.
We could alternatively do write `mat[1][1]`, which would give
the same result:

In [38]:
mat[1][1] == mat[1,1]       # don't do this!

True

This is substantially less efficient, as it first creates a
sub-dimensional array `mat[1]`, and then applies the second index
to this array.

#### Index slices

There are numerous ways to retrieve a subset of
elements from an array. The most common way is to
specify a triplet of values
`start:end:step` called `slice` for some axis:

In [39]:
# Create a 3x2 matrix
mat = np.arange(6).reshape((2,3))
mat

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
# Retrieve only the first and third columns:
mat[0:2,0:3:2]

array([[0, 2],
       [3, 5]])

Indexing with slices can get quite intricate.
Some basic rules:
- all elements of `start:end:step` are optional, with
  the obvious default values.
  We could therefore write `::` to include all indices,
  which is the same as `:`
- The end value is NOT included. Writing
  `vec[0:n]` does not include the *n*-th element!
- Any of the elements of `start:end:step` can be negative.
    - If `start` or `end` are negative, elements are counted
        backwards:
        `vec[:-1]` retrieves the vector except for the last element.
         (the end index is never included!)
    - If `step` is negative, the order of elements is inverted.

In [41]:
vec = np.arange(5)
# These are equivalent ways to return the whole vector
vec[0:5:1]      # all three components
vec[::]         # omit all components
vec[:]          # omit all components
vec[:5]         # end value only
vec[-5:]        # start value only, using negative index

array([0, 1, 2, 3, 4])

You can reverse the order like this

In [42]:
vec[::-1]

array([4, 3, 2, 1, 0])

With multi-dimensional arrays, these rules apply for each
dimension.
- We can, however, omit explicit indices
    for higher-order dimensions if all elements should
    be included.

In [43]:
mat[1]      # includes all columns of row 2; same as mat[1,:]

array([3, 4, 5])

We cannot omit the indices for preceding axis, though!

In [44]:
mat[:, 1]   # includes all rows of column 2

array([1, 4])

#### Indexing lists and tuples

The basic indexing rules we have covered so far also apply to the
built-in `tuple` and `list` types. However, `list` and `tuple`
do not support advanced indexing available for NumPy arrays
which we will study in later units.

In [45]:
# Apply start:end:step indexing to tuple
tpl = (1,2,3)
tpl[:3:2]

(1, 3)

### Numerical data types (advanced)

You can explicitly specify the numerical data type when
creating NumPy arrays.

So far we haven't done so, and then NumPy does the following:
- Functions such as `zeros()`, `ones()` and `empty()`
    default to using `np.float64`, ie. a 64-bit floating-point
    data type (this is also called *double precision*)
- Other constructors such as `arange()` and `array()`
    inspect the input data and return a corresponding array.
- Most array creation routines accept a `dtype` argument
  which allows you to explicitly set the data type.

For example:

In [46]:
# Floating-point arguments return array of type np.float64
arr = np.arange(1.0, 5.0, 1.0)
arr.dtype

dtype('float64')

In [47]:
# Integer arguments return array of type np.int64
arr = np.arange(1,5,1)
arr.dtype

dtype('int64')

Often we don't care about the data type too much, but keep in
mind that
- Floating-point has limited precision, even for integers
  larger than (approximately) $10^{16}$
- Integer values cannot represent fractional numbers and
  (often) have a more limited range.

This might lead to surprising consequences:

In [48]:
# Create integer array
arr = np.ones(5, dtype=np.int64)
# Add floating-point value 0.234 to second element in place
arr[1] += 0.234
arr

array([1, 1, 1, 1, 1])

The array is unchanged because it's impossible to represent
1.234 as an integer value!

One take-away is to always explicitly write floating-point
literal values when you want data to be interpreted as
floating-point values, eg. always write 1.0 instead of 1,
unless you really want an integer!

# Exercises

## Exercise 1: string operations

Experiment with operators applied to strings
and integers.
1.  Define two string variables and concatenate them using `+`
2.  Define a string variable and multiply it by 2 using `*`. What happens?
3.  Define two strings and compare whether they are equal using
    the `==` and `!=` relational operators.
4.  Define a string. Use the operators `in` and `not in` to
    test whether a character is contained in the string.
5.  Define two string variables and assign them the same value.
    Use the `is` operator to test whether these are identical
    objects.

## Exercise 2: string formatting

We will frequently want to create strings that incorporate
integer and floating-point data, possibly formatted in a
particular way.

Python offers quite powerful formatting capabilities, which can
become so complex that they are called the
*Format Specification Mini-Language* (see the [docs](https://docs.python.org/3/library/string.html#format-specification-mini-language)).
In this exercise we explore a small but useful subset.

A format specification is a string that contains one or several
`{}`, for example:
```
s = 'The current version of Python is {}'
```
The token `{}` will be replaced with data converted to a string
when we apply the `format()` method:
```
s = 'The current version of Python is {}'.format(3.9)
```
The string `s` now contains the value
```
'The current version of Python is 3.9'
```
What if we want to format the float `3.9` in a particular way?
We can augment the `{}` to achieve that goal. For example,
if the data to be formatted is of type integer, we can specify
-   `{:wd}` where `w` denotes the total field width and `d`
    indicates that the data type is an integer.

    To print an integer into a field that is 3 characters
    wide, we would thus write `{:3d}`.

For floats we have additional options:
-   `{:w.df}` specifies that a float should be formatted using
    a field width `w` and `d` decimal digits.

    To print a float into a field of 10 characters using 5 decimal
    digits, we would thus specify `{:10.5f}`
-   `{:w.de}` is similar, but instead uses scientific
    notation with exponents.

    This is particularly useful for very large or very small numbers.

-   `{:w.dg}` where `g` stands for general format is a superset of `f` and `e`
    formatting. Either fixed or exponential notation is used
    depending on a numbers magnitude.

In all these specifications the field width `w` is optional
and can be omitted. Python then uses however many characters are
required.

Now what we have introduced the formatting language, you
are asked to perform the following exercises:
1.  Define two strings and concatenate them using the `format()` function.
    Add a space between them.
2.  Use the above example format string, but truncate the
    Python version to its major version number, ie 3.
3.  Print $\pi$ using a precision of 10 decimal digits.
    *Hint:* one value of $\pi$ is available as
    ```
    from math import pi
    ```
4.  Print `exp(10.0)` using exponential notation and three
    decimal digits.
    *Hint:* To use the exponential function, you need to write
    ```
    from math import exp
    ```

# Solutions

## Exercise 1: string operations

In [49]:
# 1. string concatenation using addition
str1 = 'abc'
str2 = 'xyz'

# Append two strings using +
str1 + str2

'abcxyz'

In [50]:
# 2. string multiplication by integers
str1 = 'abc'
# Repeat string given number of times using multiplication
str1 * 2

'abcabc'

In [51]:
# 3. Test for string equality
str1 = 'abc'
str2 = 'xyz'
str1 == str2

False

In [52]:
# 3. Test for string inequality
str1 = 'abc'
str2 = 'xyz'
str1 != str2

True

In [53]:
# 4. Test whether individual character is included in string
str1 = 'abc'
'b' in str1

True

In [54]:
# 4. Test whether individual character is NOT included in string
str1 = 'abc'
'x' not in str1

True

The last two examples illustrate that in Python strings will
be interpreted as collections (of characters), just like lists
or tuples, if the context requires it. We can therefore apply
the `in` operator to test for membership.

In [55]:
str1 = 'abc'
str2 = 'abc'
str1 is str2

True

This result will be surprising and somewhat specific to Python.
We would not expect two objects that were created completely
independently from eachother to be *identical*, ie point to
the same memory. Python, however, caches string literals
for reasons of efficiency, so it actually does keep only *one*
copy of `'abc'` around, irrespective of how many variables
are created.

## Exercise 2: string formatting

In [56]:
# 1. String concatenation
str1 = 'abc'
str2 = 'xyz'
# format specification to concatenate two string with a space inbetween
fmt = '{} {}'
fmt.format(str1, str2)


'abc xyz'

In [57]:
# 2. Truncate Python version to major version number
# To do this, we specify 0 decimal digits!
fmt = 'The current version of Python is {:.0f}'
fmt.format(3.9)     # Now this didn't work out as intended :)

'The current version of Python is 4'

In [58]:
# 3. Print 10 using 10 decimal digits
from math import pi
fmt = 'The first 10 digits of pi: {:.10f}'
fmt.format(pi)

'The first 10 digits of pi: 3.1415926536'

In [59]:
# 4. Print exp(10.0) using three decimal digits and exponential notation
from math import exp
fmt = 'exp(10.0) = {:.3e}'
fmt.format(exp(10.0))

'exp(10.0) = 2.203e+04'